name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering of a release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Run Build
        run: |
          # Run build.py to verify and zip all packs
          python3 scripts/build.py

      - name: Upload Artifacts (Internal)
        uses: actions/upload-artifact@v4
        with:
          name: latest-build
          path: dist/*.zip
          if-no-files-found: 'error'
          retention-days: 5
          compression-level: 8

  release:
    needs: build
    # Only run this job if the workflow was triggered manually
    if: github.event_name == 'workflow_dispatch' 
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create releases
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: latest-build
          path: dist

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV #

      - name: Create and Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATE }}
          name: ${{ env.DATE }}
          files: dist/*.zip
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}